apiVersion: batch/v1
kind: CronJob
metadata:
  name: ssctl-user-plants
spec:
  schedule: "12 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ssctl-user-plants
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command:
            - /app/ssctl
            - user
            - --k8s
          restartPolicy: OnFailure